Setup
AgileTestingColombia/cypress-training pull request #1
Opened 2020-02-10 19:34 UTC by leonleo997

2020-02-10 19:34 UTC, leonleo997 commented on cypress/fixtures/example.json
> +}
EOF

2020-02-10 19:39 UTC, leonleo997 commented on cypress/fixtures/profile.json
> +}
EOF

2020-02-10 19:39 UTC, leonleo997 commented on package.json
> +    "url": "git+https://github.com/leonleo997/workshop-cypress.git"
Change URL

2020-02-10 19:39 UTC, leonleo997 commented on package.json
> +  "name": "workshop-cypress",
change name

2020-02-10 19:39 UTC, leonleo997 commented on package.json
> +    "url": "https://github.com/leonleo997/workshop-cypress/issues"
Change URL

2020-02-10 19:39 UTC, leonleo997 commented on package.json
> +  "homepage": "https://github.com/leonleo997/workshop-cypress#readme",
Change URL

2020-02-10 19:39 UTC, leonleo997 commented on .editorconfig
> +trim_trailing_whitespace = false
EOF

2020-02-10 23:18 UTC, renardete commented on cypress/fixtures/users.json
> +]
EOF y deberiamos borrar estos fixtures.

2020-02-16 21:12 UTC, leonleo997 commented
@renardete @jcruze please don't forget to review this PR

2020-02-17 12:44 UTC, renardete approved these changes

2020-02-17 13:01 UTC, holgiosalos requested changes

2020-02-17 13:01 UTC, holgiosalos commented on cypress/integration/google.spec.js
> +});
EOF

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +2. Seguir las siguientes instrucciones:
No estoy seguro de este paso, creo que también se puede hacer la momento de crear el repositorio desde GitHub. O podemos explicar mejor, y decir
"Seguir las instrucciones para realizar el primer commit, se puede realizar directamente en GitHub o alternativamente, realizar los siguientes pasos:"

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +3. Ir a Settings > Branches adicionamos una regla dando click en **add rule**. Escribimos `master` en el campo de **branch name pattern**. Una vez hecho eso, damos click en las siguientes opciones:
Aqui podemos explicar primero de que se trata el paso. Por ejemplo: 
Vamos a protejer la rama master indicando que los PR requieran revisión y la comprobación del estado antes de hacer un merge. Para hacer esto, vamos a Settings.....

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +![branch rules](https://github.com/AgileTestingColombia/cypress-training/blob/media/images/branch-rules.png).
muy buena idea la de agregar la imagen!

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +6. Ejecutar en consola `git checkout setup`.
Creo que hay un error: `git checkout -b setup`
Aqui tambien podemos explicar que vamos a hacer. Por ejemplo:
Ahora pasaremos a hacer la configuracion del proyecto, para esto creamos una rama llamada setup. (`git checkout -b setup`)

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +1. Crear un PR, asignarle los revisores y esperar por la aprobación o comentarios de los revisores. Si no sabe como realizarlo siga las siguientes [instrucciones](https://help.github.com/articles/cre
Siga las siguientes suena redundante, podemos decir "En el siguiente articulo puedes encontrar las instrucciones para crear un PR"

2020-02-17 13:01 UTC, holgiosalos commented on README.md
> +1. Una vez aprobado realizar el merge a master seleccionando la opción “squash and merge”.
Les parece si agregamos un punto adicional donde especifiquemos que una vez aprobado el PR, es importante cambiarse a master y hacer pull de los cambios, antes de comenzar con el siguiente paso?

2020-02-17 13:10 UTC, renardete commented on README.md
> +1. Una vez aprobado realizar el merge a master seleccionando la opción “squash and merge”.
Buena idea

2020-02-17 14:06 UTC, yesid-lopez reviewed
delete `google-spec`

2020-02-17 19:58 UTC, holgiosalos requested changes
En la primera sección se enumera cada paso. En las siguientes secciones no veo que hayas enumerado cada paso, creo que es bueno hacerlo por organización.

2020-02-17 19:58 UTC, holgiosalos commented on README.md
> +2. A continuación vamos a seguir las siguientes instrucciones para realizar el primer commit y subir los cambios a nuestro repositorio remoto en github:
Mejora la redacción de este punto, suena redundante al principio (A continuación vamos a **seguir** las **siguientes**).

Que tal si lo dejamos así:
Primero el paso de crear en github el repositorio.
Luego, mencionar que se debe realizar el primer commit, que hay dos opciones, siguiendo los pasos directamente en GitHub.com y la otra es creando la carpeta y siguiendo los pasos para hacer el commit local.

2020-02-17 19:58 UTC, holgiosalos commented on README.md
> +6. Creamos una nueva rama local por ejecuntando en la consola `git checkout -b setup`.
```suggestion
6. Creamos una nueva rama local ejecutando por consola el siguiente comando: `git checkout -b setup`.
```

2020-02-17 19:58 UTC, holgiosalos commented on README.md
> +1. Crear un PR, asignarle los revisores y esperar por la aprobación o comentarios de los revisores. Si no sabe como realizarlo en el siguiente articulo puedes encontrar las instrucciones para realiza
Si no sabe como **realizarlo** en el siguiente articulo puedes encontrar las instrucciones para **realizar** un Pull Request(PR)

2020-02-17 19:58 UTC, holgiosalos commented on README.md
> +1. Crear un PR, asignarle los revisores y esperar por la aprobación o comentarios de los revisores. Si no sabe como realizarlo en el siguiente articulo puedes encontrar las instrucciones para realiza
Mejor si decimos, crear un Pull Request, asignarle.....

2020-02-17 20:33 UTC, jcruze reviewed
En general veo que se esta enumerando de una manera poco comprensible, considero que deberíamos tener algo así: 
1. ....
  1.1
  1.2
2. ......
  2.1
  2.2
  .......
ó
1. .......
  a.
  b.
  c.
2. ....
 a.
 b.

2020-02-17 20:35 UTC, jcruze commented on README.md
> +2. Crear localmente una carpeta con el nombre de **cypress-training** y nos movemos dentro de la carpeta.
la enumeración punto 2.  se esta repitiendo

2020-02-18 20:21 UTC, holgiosalos approved these changes

2020-02-18 20:29 UTC, merged